### ISSUE TITLE
License for these files

### ISSUE THREAD

**Issue by Zimmi48** [jscoq/coqdoc-template#3]
Hello,
We would like to use this template for https://github.com/Zimmi48/platform-docs/. What license should be applied to these files? If your goal is to allow reuse without any restriction (i.e., without the need to copy the original license in particular), then the Unlicense is a good choice (this is what we use for https://github.com/coq-community/templates).

**Comment by ejgallego** [comment]
I'd say let's pick the license that works best for you folks.

Sorry I haven't been able to follow the platform docs effort, maybe jsCoq 2.0 would be way more useful for you?

**Comment by Zimmi48** [comment]
> I'd say let's pick the license that works best for you folks.

Great, then the Unlicense would be perfect!

> Sorry I haven't been able to follow the platform docs effort, maybe jsCoq 2.0 would be way more useful for you?

Possibly. Where can we learn about it? So far, what we have deployed (experimentally, see https://github.com/Zimmi48/platform-docs/pull/15) is based on @Villetaneuse's experience in his courses, and also imitates what has been done on the Tactician website.

**Comment by ejgallego** [comment]
> Great, then the Unlicense would be perfect!

Great, feel free to do a PR and merge.

> Possibly. Where can we learn about it? 

It is basically jsCoq ported to Flèche, we have a small demo here: https://x80.org/rhino-down/  (check what the +/- button on the top right does ;) )

So you can of course use coqdoc, but also Markdown files, etc... it is very convenient.

I didn't have time to understand what you folks try to do in the Platform docs effort, but happy to hear about your requirements and how jsCoq could be made better for you.

I wasn't planning on doing more development on jsCoq, but I'm happy to try to put some time towards this project before I wrap things up definitively.

> So far, what we have deployed (experimentally, see https://github.com/Zimmi48/platform-docs/pull/15) is based on @Villetaneuse's experience in his courses, and also imitates what has been done on the Tactician website.

Great, I'll have a look.

Note that Lasse in Tactician used jsCoq 2.0 lol, he found some experimental branch and made it work.

**Comment by Zimmi48** [comment]
> So you can of course use coqdoc, but also Markdown files, etc... it is very convenient.

Our ideal would be to keep using `.v` files so that users can download them and have all the instructions, but to be able to use a more structured language such as Markdown to do the formatting (instead of the limited coqdoc format).

>Note that Lasse in Tactician used jsCoq 2.0 lol, he found some experimental branch and made it work.

OK, that's good to hear, because this means it should be a model that we can follow then!
